spring:
  activemq:
    broker-url: tcp://localhost:61616

camel:
  component:
    kafka:
      brokers: localhost:9092
  springboot:
    message-history: true
    
camel-hello-world:
  timer-period: 15000
  log-endpoint: log:first-log